version: "3.9"

x-app-base: &app-base
  build:
    context: .
  volumes:
    - .:/app:cached
    - bundle:/usr/local/bundle
    - node_modules:/app/node_modules

services:
  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    <<: *app-base
    command: ./bin/rails server -b 0.0.0.0 -p 3400
    env_file:
      - .env
    depends_on:
      - db
      - vite
      - ssr
    ports:
      - "3400:3400"
    tty: true
    stdin_open: true

  vite:
    <<: *app-base
    command: ["yarn", "dev", "--host", "0.0.0.0", "--port", "5173"]
    environment:
      NODE_ENV: development
    ports:
      - "5173:5173"

  ssr:
    <<: *app-base
    command: ["yarn", "ssr:dev"]
    env_file:
      - .env
    ports:
      - "13714:13714"

volumes:
  postgres:
  bundle:
  node_modules:
